config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
  resources :bagel_shops, only: %i[index show]
  get 'privacy_policy', to: 'static_pages#privacy_policy'
  get 'terms_of_use', to: 'static_pages#terms_of_use'
  get 'search', to: 'application#set_search'
  get 'photos/:ref', to: 'photos#show', as: 'place_photo'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bagel_shop.rb
class BagelShop < ApplicationRecord
  validates :name, :latitude, :longitude, :place_id, presence: true, uniqueness: true

  def self.ransackable_attributes(auth_object = nil)
    ["address", "name", "rating", "user_ratings_total"]
  end

  def self.ransackable_associations(auth_object = nil)
    []
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_search
  add_flash_types :success, :info, :warning, :danger

  def set_search
    @q = BagelShop.ransack(params[:q])
    search_bagel_shops = @q.result(distinct: true)
    @bagel_shops = @q.result(distinct: true).page(params[:page])

    if params[:q].present?
      gon.clear # gonのキャッシュを防ぐため、明示的にリセット
      gon.search_bagel_shops = search_bagel_shops
    end

    return unless params[:search_button]

    if params[:q][:address_or_name_cont].blank? && params[:q][:rating_gteq].blank? && params[:q][:user_ratings_total_gteq].blank? # 検索フォームに入力があったら
      flash[:warning] = '検索フォームが入力されていません'
      redirect_back(fallback_location: root_path)
    elsif @bagel_shops.empty? # 検索結果がなかったら
      flash[:warning] = '検索結果が見つかりませんでした'
      redirect_back(fallback_location: root_path)
    end
  end
end

app/controllers/bagel_shops_controller.rb
class BagelShopsController < ApplicationController
  def index
    # @q = BagelShop.ransack(params[:q])
    # @bagel_shops = @q.result(distinct: true).page(params[:page])

    # `reset=true` が渡されたら全店舗情報を取得し直す
    if params[:reset]
      gon.reset_button_clicked = true # JS に「リセットが押された」ことを渡す
    else
      gon.reset_button_clicked = false
    end

    gon.bagel_shops = BagelShop.all
    gon.api_key = ENV["GMAPS_API_KEY"]
  end

  def show
    @bagel_shop = BagelShop.find(params[:id])
    gon.bagel_shop = @bagel_shop

    if @bagel_shop.opening_hours.present?
      @opening_hours = @bagel_shop.opening_hours.split("\n")
    end
  end
end

app/controllers/photos_controller.rb
require 'open-uri'

class PhotosController < ApplicationController
  def show
    photo_reference = params[:ref]

    url = "https://maps.googleapis.com/maps/api/place/photo?maxwidth=300&photo_reference=#{photo_reference}&key=#{ENV['GMAPS_API_KEY']}"

    begin
      image = URI.open(url)

      # 30日の間、キャッシュに保持する
      expires_in 30.days, public: true

      send_data image.read, type: image.content_type, disposition: 'inline'

    rescue OpenURI::HTTPError => e
      # エラーログを出力
      Rails.logger.error "Photo API error: #{e.message}"
      Rails.logger.error "URL attempted: #{url}"

      # 30日の間、キャッシュに保持する
      expires_in 30.days, public: true

      # 代替画像を表示
      fallback_path = Rails.root.join('public', 'images', 'no_image.jpg')
      send_file fallback_path, type: 'image/jpg', disposition: 'inline'
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def top; end
  def privacy_policy; end
  def terms_of_use; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title(title = '')
    base_title = 'Bagel Map'
    title.present? ? "#{title} | #{base_title}" : base_title
  end

  def default_meta_tags
    {
      site: 'BagelMap',
      title: 'ベーグル専門店がすぐ見つかる地図検索アプリ',
      reverse: true,
      charset: 'utf-8',
      description: 'BagelMapを使えば、美味しいベーグル専門店を地図上から簡単に検索できます。現在地から探す機能も搭載！',
      keywords: 'ベーグル,ベーグル専門店,パン屋,地図検索,現在地検索,東京,グルメ',
      canonical: request.original_url,
      separator: '|',
      og: {
        site_name: :site,
        title: :title,
        description: :description,
        type: 'website',
        url: request.original_url,
        image: image_url('ogp_bagel.png'),
        locale: 'ja_JP'
      },
      twitter: {
        card: 'summary_large_image',
        # site: '@', # Twitterアカウントがあれば記載
        image: image_url('ogp_bagel.png')
      }
    }
  end
end

app/helpers/bagel_shops_helper.rb
module BagelShopsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/bagel_shops/_shop_list.html.erb
<div class="col-sm-12 col-lg-3 mb-3">
  <div id="bagel_shop-id-<% bagel_shop.id %>">
    <div class="card">
      <% if bagel_shop.photo_references.present? %>
      <%= image_tag place_photo_path(ref: bagel_shop.photo_references.split(",").first), alt: bagel_shop.name, class: "card-img-top", width: "300", height:"300", style: "object-fit: cover;", loading: "lazy" %>
      <% else %>
      <%= image_tag "bagel_shop_placeholder.jpg", class: "card-img-top", width: "300", height: "300", style: "object-fit: cover;" %>
      <% end %>
      <div class="card-body">
        <div class="d-flex">
          <h5 class="card-title">
            <%= link_to bagel_shop.name, bagel_shop_path(bagel_shop.id) %>
          </h5>
          <!--
          <div class='ms-auto'>
            <%= link_to '#', id: "button-edit-#{bagel_shop.id}" do %>
              <i class="bi bi-pencil-fill"></i>
            <% end %>
            <%= link_to '#', id: "button-delete-#{bagel_shop.id}", method: :delete, data: {confirm: ''} do %>
              <i class="bi bi-trash-fill"></i>
            <% end %>
          </div>
          -->
        </div>
        <ul class="list-inline">
          <li><i class="fa-solid fa-store"></i><%= bagel_shop.address %></li>
          <% if bagel_shop.rating.present? %>
          <li><i class="fa-solid fa-star" style="color: #FFD43B;"></i><%= bagel_shop.rating %> (<%= bagel_shop.user_ratings_total %>)</li>
          <% else %>
          <li>評価がありません</li>
          <% end %>
          <!--
          <li><i class="fa-regular fa-calendar"></i><%= bagel_shop.opening_hours %></li>
          -->
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/bagel_shops/index.html.erb
<%= javascript_include_tag "gmap" %>
<script>
  gon.opening_shop_icon = "<%= asset_path('opening_shop_ping.png') %>";
  gon.closed_shop_icon = "<%= asset_path('closed_shop_ping.png') %>";
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GMAPS_API_KEY'] %>&callback=initMap" async defer>
</script>

<div id="loading" style="display: none;">
  <p id="loading-text" class="mb-0" style="color: #595959;">
    <span>読</span>
    <span>み</span>
    <span>込</span>
    <span>み</span>
    <span>中</span>
    <span>…</span>
  </p>
  <div class="spinner m-4"></div> <!-- スピナーのスタイルを適用 -->
</div>

<% content_for(:title, t('.title')) %>
<div class="contaner m-3">
  <div id="map" style="height:600px; width:100%;"></div>
</div>
<div class="contaner m-3">
  <h2 class="my-3 py-3 border-top border-3 border-bottom border-3 custom-border-color"><%= t('.title') %></h2>
  <div class="row">
    <%= render partial: 'shop_list', collection: @bagel_shops, as: :bagel_shop %>
  </div>
  <%= paginate @bagel_shops, theme: 'bootstrap-5' %>
</div>

app/views/bagel_shops/show.html.erb
<%= javascript_include_tag "shop_detail_map" %>
<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GMAPS_API_KEY'] %>&callback=initMap" async defer></script>

<% content_for(:title, @bagel_shop.name) %>
<div class="container mt-4">
  <div class="row">
    <div class="col-lg-7 offset-lg-2">
      <h2 class="mb-4"><%= t('.title') %></h2>

      <div class="card mb-4">
        <% if @bagel_shop.photo_references.present? %>
        <%= image_tag place_photo_path(ref: @bagel_shop.photo_references.split(",").first), alt: @bagel_shop.name, class: "card-img-top shop-image", width: "400", height: "400", style: "object-fit: cover;" %>
        <% else %>
        <%= image_tag "bagel_shop_placeholder.jpg", class: "card-img-top shop-image", width: "400", height: "400", style: "object-fit: cover;" %>
        <% end %>
      </div>

      <h3 class="mb-2"><%= @bagel_shop.name %></h3>
      <% if @bagel_shop.rating.present? %>
      <p><i class="fa-solid fa-star" style="color: #FFD43B;"></i><%= @bagel_shop.rating %> (<%= @bagel_shop.user_ratings_total %>)</p>
      <% else %>
      <p>評価がありません</p>
      <% end %>

      <div class="mb-3 shop-info-section">
        <strong>営業時間</strong>
        <% if @opening_hours.present? %>
        <% @opening_hours.each do |opening_hour| %>
        <p class="mb-0"><%= opening_hour %></p>
        <% end %>
        <% else %>
        <p>営業時間の情報がありません</p>
        <% end %>
      </div>

      <div class="mb-3 shop-info-section">
        <strong>電話番号</strong>
        <% if @bagel_shop.formatted_phone_number.present? %>
        <p><%= @bagel_shop.formatted_phone_number %></p>
        <% else %>
        <p>電話番号がありません</p>
        <% end %>
      </div>

      <div class="mb-3 shop-info-section">
        <strong>公式サイト・SNS</strong>
        <% if @bagel_shop.website.present? %>
        <p><%= link_to @bagel_shop.website, @bagel_shop.website, target: :_blank, rel: "noopener noreferrer"%></p>
        <% else %>
        <p>Webサイト・SNSがありません</p>
        <% end %>
      </div>

      <div class="mb-3 shop-info-section">
        <strong>住所</strong>
        <p><%= @bagel_shop.address %></p>
      </div>

      <div class="mb-4 shop-info-section">
        <div id="map" class="shop-map"></div>
      </div>
    </div>

    <div class="col-lg-3 mt-5 sticky-sidebar">
      <div class="list-group mb-4">
        <!--
          <%= link_to 'コメント投稿', '#', class: 'list-group-item list-group-item-action' %>
          <%= link_to 'お気に入り追加', '#', class: 'list-group-item list-group-item-action' %>
          <%= link_to 'お気に入り削除', '#', class: 'list-group-item list-group-item-action text-danger' %>
          -->
        <%= link_to "https://www.google.com/maps/dir/?api=1&destination=#{@bagel_shop.latitude}-#{@bagel_shop.longitude}&destination_place_id=#{@bagel_shop.place_id}", class: 'btn btn-route mb-2', target: :_blank, rel: "noopener noreferrer" do %>
        <i class="fa-solid fa-route"></i>ルート
        <% end %>
        <%= link_to "https://www.google.com/maps/search/?api=1&query=#{@bagel_shop.latitude}-#{@bagel_shop.longitude}&query_place_id=#{@bagel_shop.place_id}", class: 'btn btn-route', target: :_blank, rel: "noopener noreferrer" do %>
        <i class="fa-brands fa-google"></i>マップで開く
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title><%= page_title(yield(:title)) %></title>
  <%= favicon_link_tag('favicon.png') %>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= include_gon %>
  <script src="https://kit.fontawesome.com/69f6ba74fd.js" crossorigin="anonymous"></script>
  <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  <%= display_meta_tags(default_meta_tags) %>
</head>

<body>
  <%= render 'shared/header' %>

  <div id='flash-messages'>
    <%= render 'shared/flash_messages' %>
  </div>

  <%= yield %>
  <%= render 'shared/footer' %>
</body>

</html>

app/views/shared/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
<div class="alert alert-<%= message_type %> m-0">
  <%= message %>
</div>
<% end %>

app/views/shared/_footer.html.erb
<footer id='footer' class='footer-bottom' style='background-color: #A9907E'>
  <div class='container'>
    <div class='row align-items-center'>
      <div class='col'>
        <p class='m-1'>© 2024 BAGEL MAP</p>
      </div>
      <div class='col text-end'>
        <%= link_to '利用規約', terms_of_use_path, class: 'link_text me-5' %>
        <%= link_to 'プライバシー・ポリシー', privacy_policy_path, class: 'link_text me-5' %>
        <%= link_to 'お問い合わせ', 'https://forms.gle/wbYBH7aVzKSNTFGx9', target: :_blank, rel: "noopener noreferrer", class: 'link_text' %>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header class="sticky-top">
  <nav class='navbar navbar-expand-lg navigation' style='background-color: #A9907E'>

    <!-- WEBアプリロゴ -->
    <%= link_to '/', class: 'navbar-brand ms-3' do %>
    <%= image_tag 'logo.png' %>
    <% end %>

    <!-- 検索フォーム & リセットボタン -->
    <div class="container d-flex align-items-center">
      <!-- 検索フォーム -->
      <div class="flex-grow-1">
        <%= render 'shared/search_form', url: bagel_shops_path, q: @q %>

        <!-- リセットボタン -->
        <% if current_page?(bagel_shops_path) %>
        <div class="ms-auto">
          <%= link_to bagel_shops_path(reset: true), class: 'btn-reset' do %>
          <i class="fa-solid fa-rotate-right"></i> 店舗リセット
          <% end %>
        </div>
        <% end %>
      </div>
    </div>

    <%
=begin%>
    <!-- トグルボタンの設定 -->
    <button class='navbar-toggler' data-bs-toggle='collapse' data-bs-target='#navbarSupportedContent' aria-controls='navbarSupportedContent' aria-expanded='false' aria-label='Toggle navigation'>
      <span class='navbar-toggler-icon'></span>
    </button>

    <!-- リンク先 -->
    <div class='collapse navbar-collapse' id='navbarSupportedContent'>
      <ul class='navbar-nav ms-auto main-nav align-items-center'>
        <!-- アカウント登録 -->
        <li class='nav-item me-3'>
          <%= link_to 'アカウント登録', '#', class: 'nav-link link_text me-3' %>
        </li>
        <!-- ログイン -->
        <li class='nav-item'>
          <%= link_to 'ログイン', '/', class: 'nav-link btn btn-reverse me-3' %>
        </li>
      </ul>
    </div>
    <%
=end%>
  </nav>
</header>

app/views/shared/_search_form.html.erb
<div class="d-flex justify-content-between align-items-center">
  <!-- 検索フォーム -->
  <%= search_form_for @q, url: bagel_shops_path, method: :get, data: { turbo: false } do |f| %>
  <div class="search-form-container d-flex align-items-center">
    <div class="input-group">
      <%= f.search_field :address_or_name_cont, class: 'form-control auto-select', placeholder: "店舗名、地名で検索", id: 'name_or_address' %>
      <div class="input-group-append">
        <%= button_tag type: 'submit', class: 'btn btn-primary', name: 'search_button' do %>
        <i class="fa-solid fa-magnifying-glass"></i>
        <% end %>
      </div>
    </div>

    <!-- 絞り込みボタン（ドロップダウン） -->
    <div class="dropdown ms-2">
      <button class="btn btn-filter dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false" data-bs-auto-close="outside">
        <i class="fa-solid fa-filter"></i> 絞り込み
      </button>

      <!-- 絞り込みフォーム（ドロップダウンの中） -->
      <div class="dropdown-menu p-4" style="min-width: 250px;">
        <div class="mb-3">
          <%= f.label :rating, "評価" %>
          <div class="input-group">
            <%= f.number_field :rating_gteq, class: "form-control auto-select", id: "rating_form", step: "0.1", placeholder: "例: 4.0" %>
            <span class="input-group-text">以上</span>
          </div>
        </div>

        <%= f.label :user_ratings_total, "評価数" %>
        <div class="input-group">
          <%= f.number_field :user_ratings_total_gteq, class: "form-control auto-select", id: "user_ratings_total_form", placeholder: "例: 50" %>
          <span class="input-group-text">以上</span>
        </div>

        <!-- リセットボタン -->
        <div class="d-flex justify-content-end">
          <button type="button" class="btn btn-clear mt-3" id="reset-button">クリア</button>
        </div>

      </div>
    </div>
    <% end %>
  </div>

  <!-- ソート -->
  <% if current_page?(bagel_shops_path) %>
  <div class="sort-links-container">
    <%= sort_link(@q, :rating, '評価順', default_order: :desc) %>
    <%= sort_link(@q, :user_ratings_total, '評価数順', default_order: :desc) %>
    <!-- <%= sort_link(@q, :distance, '距離順') %> </div> -->
  </div>
  <% end %>

app/views/static_pages/privacy_policy.html.erb
<% content_for(:title, t('.title')) %>
<div class="container my-5">
  <h1 class="text-center mb-4"><%= t('.title') %></h1>

  <p>「BAGELMAP」（以下、「本サイト」といいます。）は、本ウェブサイト上で提供するサービス（以下、「本サービス」といいます。）における、ユーザーの個人情報の取扱いについて、以下のとおりプライバシーポリシー（以下、「本ポリシー」といいます。）を定めます。</p>

  <div class="conteiner m-5 p-5 bg-light rounded bg-opacity-75">
    <h3 class="mt-4">第1条（個人情報）</h3>
    <p>「個人情報」とは、個人情報保護法にいう「個人情報」を指すものとし、生存する個人に関する情報であって、当該情報に含まれる氏名、生年月日、住所、電話番号、連絡先その他の記述等により特定の個人を識別できる情報及び容貌、指紋、声紋にかかるデータ、及び健康保険証の保険者番号などの当該情報単体から特定の個人を識別できる情報（個人識別情報）を指します。</p>

    <h3 class="mt-4">第2条（個人情報の収集方法）</h3>
    <p>本サイトは、ユーザーが利用登録をする際にユーザー名、メールアドレスなどの個人情報をお尋ねすることがあります。</p>

    <h3 class="mt-4">第3条（個人情報を収集・利用する目的）</h3>
    <p>本サイトが個人情報を収集・利用する目的は、以下のとおりです。</p>
    <ul>
      <li>本サイトサービスの提供・運営のため</li>
      <li>ユーザーからのお問い合わせに回答するため（本人確認を行うことを含む）</li>
      <li>メンテナンス、重要なお知らせなど必要に応じたご連絡のため</li>
      <li>利用規約に違反したユーザーや、不正・不当な目的でサービスを利用しようとするユーザーの特定をし、ご利用をお断りするため</li>
      <li>ユーザーにご自身の登録情報の閲覧や変更、削除、ご利用状況の閲覧を行っていただくため</li>
      <li>上記の利用目的に付随する目的</li>
    </ul>

    <h3 class="mt-4">第4条（利用目的の変更）</h3>
    <p>本サイトは、利用目的が変更前と関連性を有すると合理的に認められる場合に限り、個人情報の利用目的を変更するものとします。利用目的の変更を行った場合には、変更後の目的について、本サイト所定の方法により、ユーザーに通知し、または本ウェブサイト上に公表するものとします。</p>

    <h3 class="mt-4">第5条（個人情報の第三者提供）</h3>
    <p>本サイトは、次に掲げる場合を除いて、あらかじめユーザーの同意を得ることなく、第三者に個人情報を提供することはありません。ただし、個人情報保護法その他の法令で認められる場合を除きます。</p>
    <ul>
      <li>人の生命、身体または財産の保護のために必要がある場合</li>
      <li>公衆衛生の向上または児童の健全な育成の推進のために特に必要がある場合</li>
      <li>国の機関もしくは地方公共団体が法令の定める事務を遂行することに対して協力する必要がある場合</li>
      <li>予め次の事項を告知し、本サイトが個人情報保護委員会に届出をしたとき</li>
    </ul>

    <h3 class="mt-4">第6条（個人情報の開示）</h3>
    <p>本サイトは、本人から個人情報の開示を求められたときは、本人に対し、遅滞なくこれを開示します。ただし、開示することにより次のいずれかに該当する場合は、その全部または一部を開示しないこともあり、その旨を通知します。</p>
    <ul>
      <li>本人または第三者の生命、身体、財産その他の権利利益を害するおそれがある場合</li>
      <li>本サイトの業務の適正な実施に著しい支障を及ぼすおそれがある場合</li>
      <li>その他法令に違反することとなる場合</li>
    </ul>

    <h3 class="mt-4">第7条（個人情報の訂正および削除）</h3>
    <p>ユーザーは、本サイトの保有する自己の個人情報が誤った情報である場合には、本サイトに対して訂正、追加または削除（以下、「訂正等」といいます。）を請求することができます。サイトはその必要があると判断した場合には、遅滞なく対応します。</p>

    <h3 class="mt-4">第8条（個人情報の利用停止等）</h3>
    <p>ユーザーは、個人情報の不正な取扱いが判明した場合、本サイトに対し、その利用停止または消去（以下、「利用停止等」といいます。）を請求できます。サイトは必要な調査を行い、速やかに対応します。</p>

    <h3 class="mt-4">第9条（プライバシーポリシーの変更）</h3>
    <p>本ポリシーの内容は、法令やサービスの変更により適宜修正されます。修正後は本サイトに掲示された時点で効力を発生します。</p>

    <h3 class="mt-4">第10条（お問い合わせ）</h3>
    <p>本ポリシーに関するお問い合わせは、<%= link_to 'こちらのフォーム', 'https://forms.gle/wbYBH7aVzKSNTFGx9', target: :_blank, rel: "noopener noreferrer" %>からお願いいたします。</p>
  </div>

  <div class="text-center mt-5">
    <%= link_to "トップページに戻る", root_path, class: 'btn btn-custom btn-lg p-3' %>
  </div>
</div>

app/views/static_pages/top.html.erb
<div class="top-wrapper">
  <div class="top-inner-text">
    <div class="mb-5">
      <h4>ベーグル食べたくありませんか?</h4>
    </div>
    <%= link_to "現在地付近のお店を探す", bagel_shops_path, class: 'btn btn-custom btn-lg p-3' %>
    <p class="fs-6">このアプリは身近のベーグル専門店を探すアプリです</p>
  </div>
</div>